# Generated by Django 3.1.5 on 2021-08-06 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgoraTokenLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=265)),
                ('appID', models.CharField(max_length=265)),
                ('creator', models.CharField(max_length=265)),
            ],
        ),
    ]
