# Generated by Django 3.1.5 on 2021-08-06 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sub', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reported_Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter', models.CharField(max_length=100)),
                ('reportee', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Reported Users',
                'verbose_name_plural': 'Reported Users',
            },
        ),
    ]
