# Generated by Django 3.1.5 on 2021-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPicker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='coinsPerAvatarPhoto',
            field=models.IntegerField(default=0, help_text='coins to deduct when user uploads more than 3 photos'),
        ),
        migrations.AlterField(
            model_name='config',
            name='coinsPerMessage',
            field=models.IntegerField(blank=True, help_text='coins deducted when user sends a message', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='coinsPerPhotoMessage',
            field=models.IntegerField(blank=True, help_text='coins deducted when user sends a photo message', null=True),
        ),
    ]
