# Generated by Django 3.1.5 on 2021-09-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photos_quota',
            field=models.SmallIntegerField(default=4),
        ),
    ]
