# Generated by Django 3.1.5 on 2021-09-12 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210911_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owned_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='fake_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
