# Generated by Django 3.1.5 on 2021-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_owned_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField()),
                ('is_admin_permission', models.BooleanField()),
                ('is_chat_admin_permission', models.BooleanField()),
            ],
        ),
    ]
